apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: applications.application.examplle.com
spec:
  group: application.examplle.com
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            applicationVersion:
              type: string
            replicas:
              format: int32
              type: integer
          required:
          - replicas
          - applicationVersion
          type: object
        status:
          properties:
            applicationVersion:
              type: string
            replicas:
              format: int32
              type: integer
          required:
          - replicas
          - applicationVersion
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
